# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-31 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('apt_address', models.CharField(max_length=30)),
                ('apt_city', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=50)),
            ],
        ),
    ]
