# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-28 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curr_res', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='username',
            field=models.CharField(default=' ', max_length=30),
        ),
    ]
