# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-28 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curr_res', '0003_auto_20180428_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent', models.IntegerField()),
                ('electricity', models.IntegerField()),
                ('gas', models.IntegerField()),
                ('due_date', models.DateField()),
                ('amount_paid', models.IntegerField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curr_res.Tenant')),
            ],
        ),
    ]
