# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-28 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20180228_1646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='officestaff',
            options={'verbose_name': 'Office Staff', 'verbose_name_plural': 'Office Staff Members'},
        ),
    ]
