# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-29 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20180428_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubhouseReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('time', models.IntegerField()),
                ('event', models.CharField(max_length=150)),
            ],
        ),
    ]
