# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-01 23:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prosp_res', '0002_auto_20180501_1956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant_prospect',
            options={'verbose_name': 'Applicant'},
        ),
    ]
